# Site settings
title:          Aeri
description:    "Note"
baseurl:        ""
url:            "https://aibia.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Aeri Jeong
  url:          https://aibia.github.io
  email:        ael_00@naver.com

# Social
facebook: "https://facebook.com/0aeri"
github: "https://github.com/Aibia"

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale